# Generated by Django 4.2.9 on 2024-04-15 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey',
            name='card',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='api.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey',
            name='trip_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fare',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='new_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='original_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
