# Generated by Django 4.2.9 on 2024-04-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_card_created_journey_card_journey_trip_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created',
        ),
    ]
