# Generated by Django 4.2.9 on 2024-04-15 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_card_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
